### ISSUE TITLE
Text Encoding Issues on Windows

### ISSUE THREAD

**Issue by urig** [vishal180618/OLTP-AdventureWorks2019-MySQL#1]
Hi @vishal180618. Thanks for creating this port of AdventureWorks 2019 to MySQL.

Using MySQL Workbench 8.0.26 on Windows, I am unable to get the script to run without critical errors.

### Steps to reproduce:
1. Download `AdventureWorks2019.7z`.
2. Unzip `AdventureWorks2019.sql`.
3. In the Workbench, open the file using *File > Open SQL Script*.
4. A dialog is shown, title "Unknown File Encoding":
 
    ![image](https://user-images.githubusercontent.com/350687/202989560-8723d7b9-b6f3-4171-9db6-1c3625cde163.png)

    Please note that the dialog says "The file ... is not UTF-8 encoded."
5. Click on the button titled "Run SQL Script..."
6. A new dialog opens. Enter default schema name and choose "utf8" as the default character set.
    ![image](https://user-images.githubusercontent.com/350687/202990281-a8c732c8-ed9f-4431-8421-2859d3b6db76.png)
8. Click on "Run".

### Expected results:
The script should run successfully and the database should be created fully.

### Actual results:
An error box is shown, saying:
> Error executing SQL script
> sequence item 7:  expected str instance, bytes found

![image](https://user-images.githubusercontent.com/350687/202990843-1f2e7783-72e4-4ee5-be6d-eb48adccd13e.png)

Thanks and please let me know if I can help in resolving this issue.

**Comment by vishal180618** [comment]
did you try importing it?
https://dev.mysql.com/doc/workbench/en/wb-admin-export-import-management.html

**Comment by urig** [comment]
Thank you. I tried importing it through the Workbench's Data Import feature and that went smoothly.
